import json
import matplotlib.pyplot as plt
import numpy as np

def plot_fitness():
    # Load the aggregated data generated by multi_seed_run.py
    with open("multi_seed_aggregated.json", "r") as f:
        data = json.load(f)

    generations = np.array(data["generations"])
    n_seeds = data["n_seeds"]

    # Extract means and standard deviations
    best_mean = np.array(data["best_mean_over_seeds"])
    best_std = np.array(data["best_std_over_seeds"])

    mean_mean = np.array(data["mean_mean_over_seeds"])
    mean_std = np.array(data["mean_std_over_seeds"])

    worst_mean = np.array(data["worst_mean_over_seeds"])
    worst_std = np.array(data["worst_std_over_seeds"])

    # Create the figure
    plt.figure(figsize=(9, 6))

    # 1. Plot Best Fitness (Green)
    plt.plot(generations, best_mean, label='best (mean +/- std)', color='#2ca02c', linewidth=2)
    plt.fill_between(generations, best_mean - best_std, best_mean + best_std, color='#2ca02c', alpha=0.2)

    # 2. Plot Population Mean Fitness (Orange)
    plt.plot(generations, mean_mean, label='population mean (mean +/- std)', color='#ff7f0e', linewidth=2)
    plt.fill_between(generations, mean_mean - mean_std, mean_mean + mean_std, color='#ff7f0e', alpha=0.2)

    # 3. Plot Worst Fitness (Red)
    plt.plot(generations, worst_mean, label='worst (mean +/- std)', color='#d62728', linewidth=2)
    plt.fill_between(generations, worst_mean - worst_std, worst_mean + worst_std, color='#d62728', alpha=0.2)

    # Format the plot to match the reference image
    plt.title(f'Fitness over generations, aggregated across {n_seeds} independent seeds')
    plt.xlabel('Generation')
    plt.ylabel('Fitness')
    
    # Add a light grid
    plt.grid(True, linestyle='-', alpha=0.4)
    
    # Position the legend in the lower right
    plt.legend(loc='lower right')

    # Save and display
    plt.tight_layout()
    plt.savefig('fitness_aggregation_plot.png', dpi=300)
    plt.show()


def plot_generalization():
    # Load the summary data generated by multi_seed_run.py
    try:
        with open("multi_seed_summary.json", "r") as f:
            summary_data = json.load(f)
    except FileNotFoundError:
        print("Error: multi_seed_summary.json not found. Run multi_seed_run.py first.")
        return

    # Extract data for the plot
    seeds = [row["seed"] for row in summary_data]
    best_fitness = [row["best_fitness"] for row in summary_data]
    # Convert success rate to a percentage to match the y-axis
    holdout_rate = [row["holdout_success_rate"] * 100 for row in summary_data]

    # Create the figure
    plt.figure(figsize=(9, 6))

    # Plot each seed individually to color and annotate them
    for s, x, y in zip(seeds, best_fitness, holdout_rate):
        # Color logic: Green for high success, red for low (matching the image)
        point_color = '#2ca02c' if y > 50 else '#c0392b' 
        
        plt.scatter(x, y, color=point_color, s=80, zorder=3)
        
        # Add the "seed X" annotation with a slight offset so it doesn't overlap the dot
        plt.annotate(f"seed {s}", (x, y), 
                     xytext=(7, 5), 
                     textcoords='offset points',
                     fontsize=9,
                     color='black')

    # Formatting to match the reference image
    plt.title('Training fitness vs. generalization, per seed\n(near-identical training fitness does not guarantee generalization)')
    plt.xlabel('Best training fitness')
    plt.ylabel('Held-out success rate (%)')
    
    # Add a light grid (zorder=0 puts it behind the scatter points)
    plt.grid(True, linestyle='-', alpha=0.3, zorder=0)
    
    # Adjust layout and save
    plt.tight_layout()
    plt.savefig('fitness_vs_generalization_scatter.png', dpi=300)
    plt.show()


    
if __name__ == "__main__":
    plot_fitness()
    plot_generalization()